#!/usr/bin/env bash
#
# Deploys a CPP vault to Stellar testnet and writes a ready-to-use .env.
#
#   ./scripts/deploy.sh                   1 XLM denomination, fresh mint key
#   ./scripts/deploy.sh --denom 50000000  5 XLM
#   ./scripts/deploy.sh --seed <64-hex>   reuse an existing mint seed
#
# Creates four identities so the demo can show what the chain does and does not
# link: `cpp-mint` signs `announce`, `cpp-alice` deposits, `cpp-relayer` submits
# redemptions, and `cpp-sponsor` creates the accounts redemptions pay into.
# Alice and the relayer are unrelated accounts, which is the point — the account
# that pays for a redemption proves nothing about who owns the token.
#
# These four are operator accounts, provisioned once and openly. Friendbot is
# fine for them: they are *meant* to be identifiable, and on mainnet you would
# fund them out of band. It is the per-redemption *recipient* accounts that must
# not be traceable to a depositor, which is why those go through `cpp-sponsor`
# (see ts/src/sponsor.ts) instead.

set -euo pipefail

cd "$(dirname "$0")/.."

NETWORK="${STELLAR_NETWORK:-testnet}"
DENOMINATION="10000000" # 1 XLM in stroops
MINT_SEED=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --denom) DENOMINATION="$2"; shift 2 ;;
    --seed)  MINT_SEED="$2";    shift 2 ;;
    --network) NETWORK="$2";    shift 2 ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
done

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# ---------------------------------------------------------------------------

say "Checking toolchain"
command -v stellar >/dev/null || { echo "stellar CLI not found"; exit 1; }
command -v node    >/dev/null || { echo "node not found"; exit 1; }
stellar --version | head -1
node --version

say "Creating and funding identities on $NETWORK"
for name in cpp-mint cpp-alice cpp-relayer cpp-sponsor; do
  if ! stellar keys address "$name" >/dev/null 2>&1; then
    stellar keys generate "$name" --network "$NETWORK" --fund
    echo "  generated $name"
  else
    # Already exists; top it up so a re-run of the demo has fees to spend.
    stellar keys fund "$name" --network "$NETWORK" >/dev/null 2>&1 || true
    echo "  reusing   $name"
  fi
  printf '            %s\n' "$(stellar keys address "$name")"
done

MINT_ADDRESS="$(stellar keys address cpp-mint)"
ALICE_ADDRESS="$(stellar keys address cpp-alice)"
RELAYER_ADDRESS="$(stellar keys address cpp-relayer)"
SPONSOR_ADDRESS="$(stellar keys address cpp-sponsor)"

say "Deriving the mint's BLS12-381 key"
if [[ -z "$MINT_SEED" ]]; then
  MINT_SEED="$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))')"
  echo "  generated a fresh seed"
else
  echo "  using the seed provided on the command line"
fi
MINT_PK="$(npm --prefix ts run --silent mintkey -- --seed "$MINT_SEED" --pk-only)"
echo "  pk (G2) ${MINT_PK:0:32}…"

say "Resolving the native XLM Stellar Asset Contract"
TOKEN_ID="$(stellar contract id asset --asset native --network "$NETWORK")"
echo "  $TOKEN_ID"

say "Building the contract"
stellar contract build
WASM="target/wasm32v1-none/release/cpp_vault.wasm"
echo "  $WASM ($(wc -c < "$WASM" | tr -d ' ') bytes)"

say "Deploying"
# The constructor validates `mint_pk` as a G2 subgroup element, so a botched
# key fails here rather than at the first redemption.
VAULT_ID="$(stellar contract deploy \
  --wasm "$WASM" \
  --source cpp-mint \
  --network "$NETWORK" \
  -- \
  --mint_authority "$MINT_ADDRESS" \
  --mint_pk "$MINT_PK" \
  --token "$TOKEN_ID" \
  --denomination "$DENOMINATION")"

echo "  $VAULT_ID"

say "Writing .env"
cat > .env <<EOF
# Generated by scripts/deploy.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

STELLAR_NETWORK=$NETWORK
VAULT_CONTRACT_ID=$VAULT_ID

# Mint. MINT_SEED is the signing key for every token this vault will ever
# honour — treat it like a hot wallet key, and do not commit this file.
MINT_AUTHORITY_SECRET=$(stellar keys secret cpp-mint)
MINT_SEED=$MINT_SEED

# Screening policy. Without at least one of these the mint signs everything.
CPP_DENYLIST_FILE=scripts/denylist.json

# Demo accounts.
DEPOSITOR_SECRET=$(stellar keys secret cpp-alice)
SUBMITTER_SECRET=$(stellar keys secret cpp-relayer)

# Puts up the base reserve for every recipient account a redemption pays into.
# One shared sponsor, never the depositor — see ts/src/sponsor.ts.
SPONSOR_SECRET=$(stellar keys secret cpp-sponsor)
EOF
chmod 600 .env

say "Done"
cat <<EOF
  vault        $VAULT_ID
  token        $TOKEN_ID (native XLM)
  denomination $DENOMINATION stroops
  mint         $MINT_ADDRESS
  alice        $ALICE_ADDRESS
  relayer      $RELAYER_ADDRESS
  sponsor      $SPONSOR_ADDRESS

Next:
  1. start the mint:   npm --prefix ts run mint
  2. run the demo:     ./scripts/demo.sh
EOF
